### ISSUE TITLE
Passing an object to addChildTargetFn causes an error.

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#158]

**Comment by jvivian** [comment]
I can pass strings, lists, sets, dicts and other variables, but I cannot pass objects. 

If I do, I get the following importError with the scripts file name as module it's trying to import.
```
WARNING:jobTree.leader:M/6/jobzF3QJ3:   ---JOBTREE WORKER OUTPUT LOG---
WARNING:jobTree.leader:M/6/jobzF3QJ3:   Traceback (most recent call last):
WARNING:jobTree.leader:M/6/jobzF3QJ3:     File "/Users/Jvivian/Dropbox/School/PhD/Projects/jobTree/src/jobTree/worker.py", line 265, in main
WARNING:jobTree.leader:M/6/jobzF3QJ3:       messages = loadTarget(job.command,jobStore)._execute(job=job,
WARNING:jobTree.leader:M/6/jobzF3QJ3:     File "/Users/Jvivian/Dropbox/School/PhD/Projects/jobTree/src/jobTree/worker.py", line 84, in loadTarget
WARNING:jobTree.leader:M/6/jobzF3QJ3:       return cPickle.load( fileHandle )
WARNING:jobTree.leader:M/6/jobzF3QJ3:   ImportError: No module named helloWorld
WARNING:jobTree.leader:M/6/jobzF3QJ3:   Exiting the worker because of a failed job on host Johns-MacBook-Pro.local
WARNING:jobTree.leader:M/6/jobzF3QJ3:   ERROR:__main__:Exiting the worker because of a failed job on host Johns-MacBook-Pro.local
WARNING:jobTree.leader:M/6/jobzF3QJ3:   WARNING:jobTree.job:Due to failure we are reducing the remaining retry count of job M/6/jobzF3QJ3 to 0
```

**Comment by jvivian** [comment]
I should also mention, this is on the dag-rebased branch.

**Comment by jvivian** [comment]
Intended behavior; closing.
