### ISSUE TITLE
cgcloud race condition

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/slugflow#182]
Warning: sudo() received nonzero return code 100 while executing 'DEBIAN_FRONTEND=readline apt-get -q -y update'!

WARNING: Detected race condition during in '%s'
INFO: Terminating instance ...
INFO: ... instance terminated.
Traceback (most recent call last):
  File "/usr/local/bin/cgcloud", line 9, in <module>
    load_entry_point('cgcloud-core==1.0.dev9', 'console_scripts', 'cgcloud')()
  File "/Users/cj/cgcloud/core/src/cgcloud/core/ui.py", line 24, in main
    app.run( args )
  File "/Users/cj/cgcloud/lib/src/cgcloud/lib/util.py", line 203, in run
    command.run( options )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/commands.py", line 77, in run
    return self.run_in_ctx( options, ctx )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/commands.py", line 112, in run_in_ctx
    return self.run_on_box( options, box )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/commands.py", line 394, in run_on_box
    box.terminate( wait=False )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/cj/cgcloud/core/src/cgcloud/core/commands.py", line 390, in run_on_box
    self.run_on_creation( box, options )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/commands.py", line 573, in run_on_creation
    box.setup( upgrade_installed_packages=options.upgrade )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/package_manager_box.py", line 85, in setup
    self._sync_package_repos( )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/box.py", line 59, in wrapper
    return box._execute_task( task, user )
  File "/Users/cj/cgcloud/core/src/cgcloud/core/box.py", line 679, in _execute_task
    return execute( task, hosts=[ host ] )[ host ]
  File "/Library/Python/2.7/site-packages/Fabric-1.10.1-py2.7.egg/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/Library/Python/2.7/site-packages/Fabric-1.10.1-py2.7.egg/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/Fabric-1.10.1-py2.7.egg/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/cj/cgcloud/core/src/cgcloud/core/ubuntu_box.py", line 87, in _sync_package_repos
    raise RuntimeError( "Command '%s' repeatedly failed with race condition. Giving up." )
RuntimeError: Command '%s' repeatedly failed with race condition. Giving up.

**Comment by cket** [comment]
I've seen this happen when creating both ubuntu and mesos boxes.

**Comment by cket** [comment]
The code that throws this error reveals that this is a known problem with apt_get updating, and provides the following links for more information

https://bugs.launchpad.net/ubuntu/+source/apt/+bug/972077
https://lists.debian.org/debian-dak/2012/05/threads.html#00006

**Comment by cket** [comment]
It fixed itself, I think it had to do with mesos releasing version 0.23. I don't think there is anything we can do to prevent this, so I am closing the issue
