### ISSUE TITLE
Error in jobTreeStats caused by change in fileHandle object

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/slugflow#89]
To reproduce error run tests/utils/statsTest.py

```
Traceback (most recent call last):
  File "/Users/benedictpaten/sync/eclipse/git/jobTree/bin/jobTreeStats", line 759, in <module>
    main()
  File "/Users/benedictpaten/sync/eclipse/git/jobTree/bin/jobTreeStats", line 748, in main
    stats = getStats(options)
  File "/Users/benedictpaten/sync/eclipse/git/jobTree/bin/jobTreeStats", line 562, in getStats
    stats = ET.parse(fH).getroot() # Try parsing the whole file.
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
TypeError: coercing to Unicode: need string or buffer, GeneratorContextManager found
```

**Comment by hannes-ucsc** [comment]
Can't reproduce. Did you remember to run "make scripts" to update the copies in the bin directory?
